server:
  port: 8080

slow-sql-monitor:
  slow-millis: 1000
  log-slow-sql: false
  elasticsearch:
    enabled: true
    uris: https://127.0.0.1:9200
    username: elastic
    password: 123456
    sendMillis: 0

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.10:3306/ase_release?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
      username: ase
      password: fEJ0CnDop54mQYB!
      initial-size: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      validationQuery: SELECT 1

